# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import travel_agency_pb2 as travel__agency__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in travel_agency_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTour = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/AddTour',
                request_serializer=travel__agency__pb2.AddTourRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.TourResponse.FromString,
                _registered_method=True)
        self.UpdateTour = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/UpdateTour',
                request_serializer=travel__agency__pb2.UpdateTourRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.TourResponse.FromString,
                _registered_method=True)
        self.GetTour = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/GetTour',
                request_serializer=travel__agency__pb2.TourIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.TourResponse.FromString,
                _registered_method=True)
        self.ListTours = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/ListTours',
                request_serializer=travel__agency__pb2.Empty.SerializeToString,
                response_deserializer=travel__agency__pb2.TourListResponse.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/RegisterClient',
                request_serializer=travel__agency__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.GetClient = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/GetClient',
                request_serializer=travel__agency__pb2.ClientIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.ClientResponse.FromString,
                _registered_method=True)
        self.ListClients = channel.unary_unary(
                '/travel_agency.lab4.ReferenceService/ListClients',
                request_serializer=travel__agency__pb2.Empty.SerializeToString,
                response_deserializer=travel__agency__pb2.ClientListResponse.FromString,
                _registered_method=True)


class ReferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTours(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTour': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTour,
                    request_deserializer=travel__agency__pb2.AddTourRequest.FromString,
                    response_serializer=travel__agency__pb2.TourResponse.SerializeToString,
            ),
            'UpdateTour': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTour,
                    request_deserializer=travel__agency__pb2.UpdateTourRequest.FromString,
                    response_serializer=travel__agency__pb2.TourResponse.SerializeToString,
            ),
            'GetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTour,
                    request_deserializer=travel__agency__pb2.TourIdRequest.FromString,
                    response_serializer=travel__agency__pb2.TourResponse.SerializeToString,
            ),
            'ListTours': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTours,
                    request_deserializer=travel__agency__pb2.Empty.FromString,
                    response_serializer=travel__agency__pb2.TourListResponse.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=travel__agency__pb2.RegisterClientRequest.FromString,
                    response_serializer=travel__agency__pb2.ClientResponse.SerializeToString,
            ),
            'GetClient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClient,
                    request_deserializer=travel__agency__pb2.ClientIdRequest.FromString,
                    response_serializer=travel__agency__pb2.ClientResponse.SerializeToString,
            ),
            'ListClients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClients,
                    request_deserializer=travel__agency__pb2.Empty.FromString,
                    response_serializer=travel__agency__pb2.ClientListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel_agency.lab4.ReferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel_agency.lab4.ReferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/AddTour',
            travel__agency__pb2.AddTourRequest.SerializeToString,
            travel__agency__pb2.TourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/UpdateTour',
            travel__agency__pb2.UpdateTourRequest.SerializeToString,
            travel__agency__pb2.TourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/GetTour',
            travel__agency__pb2.TourIdRequest.SerializeToString,
            travel__agency__pb2.TourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/ListTours',
            travel__agency__pb2.Empty.SerializeToString,
            travel__agency__pb2.TourListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/RegisterClient',
            travel__agency__pb2.RegisterClientRequest.SerializeToString,
            travel__agency__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/GetClient',
            travel__agency__pb2.ClientIdRequest.SerializeToString,
            travel__agency__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.ReferenceService/ListClients',
            travel__agency__pb2.Empty.SerializeToString,
            travel__agency__pb2.ClientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/travel_agency.lab4.CoreService/CreateBooking',
                request_serializer=travel__agency__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.StartBookingProcessing = channel.unary_unary(
                '/travel_agency.lab4.CoreService/StartBookingProcessing',
                request_serializer=travel__agency__pb2.BookingIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.MarkBookingReady = channel.unary_unary(
                '/travel_agency.lab4.CoreService/MarkBookingReady',
                request_serializer=travel__agency__pb2.BookingIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.IssueBooking = channel.unary_unary(
                '/travel_agency.lab4.CoreService/IssueBooking',
                request_serializer=travel__agency__pb2.BookingIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/travel_agency.lab4.CoreService/CancelBooking',
                request_serializer=travel__agency__pb2.BookingIdRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.RecordPayment = channel.unary_unary(
                '/travel_agency.lab4.CoreService/RecordPayment',
                request_serializer=travel__agency__pb2.PaymentRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingOperationResponse.FromString,
                _registered_method=True)
        self.ListBookings = channel.unary_unary(
                '/travel_agency.lab4.CoreService/ListBookings',
                request_serializer=travel__agency__pb2.Empty.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingListResponse.FromString,
                _registered_method=True)
        self.CheckExpiredBookings = channel.unary_unary(
                '/travel_agency.lab4.CoreService/CheckExpiredBookings',
                request_serializer=travel__agency__pb2.CheckExpiredBookingsRequest.SerializeToString,
                response_deserializer=travel__agency__pb2.BookingListResponse.FromString,
                _registered_method=True)
        self.RenderMarketingReport = channel.unary_unary(
                '/travel_agency.lab4.CoreService/RenderMarketingReport',
                request_serializer=travel__agency__pb2.Empty.SerializeToString,
                response_deserializer=travel__agency__pb2.TextResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBookingProcessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkBookingReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExpiredBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderMarketingReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=travel__agency__pb2.CreateBookingRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'StartBookingProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBookingProcessing,
                    request_deserializer=travel__agency__pb2.BookingIdRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'MarkBookingReady': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkBookingReady,
                    request_deserializer=travel__agency__pb2.BookingIdRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'IssueBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueBooking,
                    request_deserializer=travel__agency__pb2.BookingIdRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=travel__agency__pb2.BookingIdRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'RecordPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPayment,
                    request_deserializer=travel__agency__pb2.PaymentRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingOperationResponse.SerializeToString,
            ),
            'ListBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookings,
                    request_deserializer=travel__agency__pb2.Empty.FromString,
                    response_serializer=travel__agency__pb2.BookingListResponse.SerializeToString,
            ),
            'CheckExpiredBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExpiredBookings,
                    request_deserializer=travel__agency__pb2.CheckExpiredBookingsRequest.FromString,
                    response_serializer=travel__agency__pb2.BookingListResponse.SerializeToString,
            ),
            'RenderMarketingReport': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderMarketingReport,
                    request_deserializer=travel__agency__pb2.Empty.FromString,
                    response_serializer=travel__agency__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel_agency.lab4.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel_agency.lab4.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/CreateBooking',
            travel__agency__pb2.CreateBookingRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBookingProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/StartBookingProcessing',
            travel__agency__pb2.BookingIdRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkBookingReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/MarkBookingReady',
            travel__agency__pb2.BookingIdRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/IssueBooking',
            travel__agency__pb2.BookingIdRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/CancelBooking',
            travel__agency__pb2.BookingIdRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/RecordPayment',
            travel__agency__pb2.PaymentRequest.SerializeToString,
            travel__agency__pb2.BookingOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/ListBookings',
            travel__agency__pb2.Empty.SerializeToString,
            travel__agency__pb2.BookingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckExpiredBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/CheckExpiredBookings',
            travel__agency__pb2.CheckExpiredBookingsRequest.SerializeToString,
            travel__agency__pb2.BookingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderMarketingReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel_agency.lab4.CoreService/RenderMarketingReport',
            travel__agency__pb2.Empty.SerializeToString,
            travel__agency__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
